version: 2
updates:
- package-ecosystem: cargo
  directory: /
  assignees:
    - shish
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
