[package]
name = "packetstats"
version = "0.1.0"
authors = ["Shish <shish@shishnet.org>"]
edition = "2018"

[dependencies]
pcap = "2.2.0"
argparse = "0.2.2"
etherparse = "0.18.0"
dns-lookup = "2.0.4"
anyhow = "1.0.98"
