name: Build

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v7
    - run: sudo apt install -y libpcap-dev
    - run: cargo build --release
